# frozen_string_literal: true
source "https://rubygems.org"

gem "activerecord"
gem "sinatra-activerecord"
gem "sqlite3"
gem "dotenv"
gem "httparty"
gem "gtfs-realtime-bindings"
gem "protobuf"
gem "pry"
gem "pry-byebug"
gem "require_all"
gem "artii"
gem "tty-prompt"